name: Release Canary Version

on:
  push:
    branches:
      - build/ci
      - ci/*

jobs:
  release_canary:
    name: Prepare branch and release Canary version
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure CI Git User
        run: |
          git config --global user.name 'Danilo Velasquez'
          git config --global user.email 'danilo.velasquez@gmail.com'
          git remote set-url origin https://$GITHUB_TOKEN@github.com/dvelasquez/carbon-tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: build
        run: yarn run lerna:build
      - name: Bootstrap dependencies
        run: yarn run lerna:bootstrap
      - name: Run Node TAP tests
        run: yarn run test
      - name: Version
        run: yarn run lerna:version
      - name: NPM Auth
        run: |
          yarn logout
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc 2> /dev/null
          npm whoami
          npm config set access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish package
        run: npm run lerna:deploy:ci:canary
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


